source 'https://github.com/CocoaPods/Specs.git'

target 'YouTubeLiveVideo' do

platform :ios, '9.0'
use_frameworks!

#pod 'YTLiveStreaming', :path => '../.'
pod 'YTLiveStreaming'
pod "XCDYouTubeKit", "~> 2.5"

end
