source 'https://github.com/CocoaPods/Specs.git'

target 'YouTubeLiveVideo' do
    
    platform :ios, '11.0'
    use_frameworks!
    
    pod 'GoogleSignIn'
    # Use the framework from repo:
#    pod 'YTLiveStreaming' "~> 0.2.14"
    # But You can use the local copy just for development:
    pod 'YTLiveStreaming', :path => '../.'

    pod "XCDYouTubeKit", "~> 2.5"
    
end
